BEGIN;

CREATE SCHEMA IF NOT EXISTS products;

CREATE TABLE products.product (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    categories VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    inventory INT NOT NULL,
    imageUrl VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;