version: "2"
sql:
  - schema: "../../../db/migrations/000001_init_account.up.sql"
    queries: "query.sql"
    engine: "postgresql"
    gen:
      go:
        package: "postgresql"
        out: "postgresql"
        emit_json_tags: true