// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresql

import (
	"database/sql"
)

type ProductsProduct struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Categories string         `json:"categories"`
	Price      int64          `json:"price"`
	Inventory  int32          `json:"inventory"`
	Imageurl   sql.NullString `json:"imageurl"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}
