// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ProductsProduct struct {
	ID          uuid.UUID             `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	BasePrice   int64                 `json:"base_price"`
	ImageUrl    sql.NullString        `json:"image_url"`
	Category    sql.NullString        `json:"category"`
	Options     pqtype.NullRawMessage `json:"options"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}
